version: '2.3'

services:
  backup-agent:
    image: aerondigth/backup-agent:0.0.8
    privileged: true

    volumes:
      - /home/halstein/valheim_worlds_local:/valheim_worlds_local:z

    ports:
    - "${backup.http_port}:${backup.http_port}/tcp"

    environment:
    - BACKUP_CRON=${backup.cron}
    - BACKUP_DIR=/valheim_worlds_local
    - BUCKET_ID=${ backup.bucket_id }
    - OBJECT_ID=${ env.world_name }
    - HTTP_PORT=${ backup.http_port }
    - AWS_ACCESS_KEY_ID=${s3AccessKeyId}
    - AWS_SECRET_ACCESS_KEY=${s3AccessKeySecret}
    - AWS_REGION=ru-central1

  valheim-server:
    image: lloesche/valheim-server
    privileged: true
    volumes:
      - /home/halstein/valheim_worlds_local:/home/valheim/.config/unity3d/IronGate/Valheim/worlds_local:z
    
    ports:
    - "8080:8080/tcp"
    - "8082:8082/tcp"
    - "2456:2456/udp"
    - "2457:2457/udp"

    environment:
    - SUPERVISOR_HTTP=${supervisor.supervisor_http}
    - SUPERVISOR_HTTP_PORT=${supervisor.supervisor_http_port}
    - SUPERVISOR_HTTP_USER=${supervisor.supervisor_http_user}
    - SUPERVISOR_HTTP_PASS=${supervisor.supervisor_http_pass}
    - SERVER_NAME=${ env.server_name }
    - SERVER_PASS=${ env.server_pass }
    - SERVER_PUBLIC=${ env.server_public }
    - WORLD_NAME=${ env.world_name }
    - ADMINLIST_IDS='${ join(" ", env.adminlist_ids) }'
    - TZ=${ env.tz }
    - BACKUPS=false
    - BACKUPS_MAX_AGE=3
    - BACKUPS_MAX_COUNT=100
    - STATUS_HTTP=true
    - STATUS_HTTP_PORT=8082

